// Code generated by MockGen. DO NOT EDIT.
// Source: internal/encoder/url_storager.go

// Package mock_encoder is a generated GoMock package.
package mock_encoder

import (
	context "context"
	reflect "reflect"

	models "github.com/0xc00000f/shortener-tpl/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockURLStorager is a mock of URLStorager interface.
type MockURLStorager struct {
	ctrl     *gomock.Controller
	recorder *MockURLStoragerMockRecorder
}

// MockURLStoragerMockRecorder is the mock recorder for MockURLStorager.
type MockURLStoragerMockRecorder struct {
	mock *MockURLStorager
}

// NewMockURLStorager creates a new mock instance.
func NewMockURLStorager(ctrl *gomock.Controller) *MockURLStorager {
	mock := &MockURLStorager{ctrl: ctrl}
	mock.recorder = &MockURLStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStorager) EXPECT() *MockURLStoragerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockURLStorager) Delete(ctx context.Context, data []models.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLStoragerMockRecorder) Delete(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLStorager)(nil).Delete), ctx, data)
}

// Get mocks base method.
func (m *MockURLStorager) Get(ctx context.Context, short string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, short)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLStoragerMockRecorder) Get(ctx, short interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLStorager)(nil).Get), ctx, short)
}

// GetAll mocks base method.
func (m *MockURLStorager) GetAll(ctx context.Context, userID uuid.UUID) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockURLStoragerMockRecorder) GetAll(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockURLStorager)(nil).GetAll), ctx, userID)
}

// GetStats mocks base method.
func (m *MockURLStorager) GetStats(ctx context.Context) (models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockURLStoragerMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockURLStorager)(nil).GetStats), ctx)
}

// IsKeyExist mocks base method.
func (m *MockURLStorager) IsKeyExist(ctx context.Context, short string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsKeyExist", ctx, short)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsKeyExist indicates an expected call of IsKeyExist.
func (mr *MockURLStoragerMockRecorder) IsKeyExist(ctx, short interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsKeyExist", reflect.TypeOf((*MockURLStorager)(nil).IsKeyExist), ctx, short)
}

// Store mocks base method.
func (m *MockURLStorager) Store(ctx context.Context, userID uuid.UUID, short, long string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, short, long)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockURLStoragerMockRecorder) Store(ctx, userID, short, long interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockURLStorager)(nil).Store), ctx, userID, short, long)
}
